"""empty message

Revision ID: 08ed5d2fab62
Revises: 975eabe80445
Create Date: 2021-09-12 21:32:41.182525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ed5d2fab62'
down_revision = '975eabe80445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
