"""empty message

Revision ID: 163514ebf0fc
Revises: 21afdf577c45
Create Date: 2022-02-09 12:56:13.243249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '163514ebf0fc'
down_revision = '21afdf577c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booksapp_booksubjects',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('book_subject', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('booksapp_userpntoken',
    sa.Column('token_id', sa.BigInteger(), nullable=False),
    sa.Column('usernumber', sa.BigInteger(), nullable=False),
    sa.Column('devicetoken', sa.Text(), nullable=False),
    sa.Column('awsarnendpoint', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('token_id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booksapp_userpntoken')
    op.drop_table('booksapp_booksubjects')
    # ### end Alembic commands ###
