"""empty message

Revision ID: 21afdf577c45
Revises: b8f4ab8a7c68
Create Date: 2022-02-07 14:19:23.405072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21afdf577c45'
down_revision = 'b8f4ab8a7c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booksapp_users', 'verified', new_column_name='email_verified')
    op.alter_column('booksapp_users', 'verified_on', new_column_name='email_verified_on')
    op.add_column('booksapp_book', sa.Column('book_isbn', sa.String(length=15), nullable=True))
    op.add_column('booksapp_book', sa.Column('book_category', sa.String(length=20), nullable=True))
    op.add_column('booksapp_users', sa.Column('phn_verified', sa.Boolean(), nullable=True))
    op.add_column('booksapp_users', sa.Column('phn_verified_on', sa.DateTime(), nullable=True))
    op.add_column('booksapp_users', sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booksapp_users', 'email_verified', new_column_name='verified')
    op.alter_column('booksapp_users', 'email_verified_on', new_column_name='verified_on')
    op.drop_column('booksapp_users', 'phn_verified_on')
    op.drop_column('booksapp_users', 'phn_verified')
    op.drop_column('booksapp_book', 'book_category')
    op.drop_column('booksapp_book', 'book_isbn')
    op.drop_column('booksapp_users', 'last_active')
    # ### end Alembic commands ###
