"""empty message

Revision ID: 51850e5170c6
Revises: edba09ee86b1
Create Date: 2022-03-08 13:09:34.651749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51850e5170c6'
down_revision = 'edba09ee86b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booksapp_transaction', sa.Column('transaction_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booksapp_transaction', 'transaction_type')
    # ### end Alembic commands ###
