"""empty message

Revision ID: 589526d1d923
Revises: 51850e5170c6
Create Date: 2022-04-26 13:58:39.958605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589526d1d923'
down_revision = '51850e5170c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booksapp_transaction', sa.Column('transaction_book_ts', sa.DateTime(), nullable=True))
    op.add_column('booksapp_transaction', sa.Column('transaction_remove_ts', sa.DateTime(), nullable=True))
    op.add_column('booksapp_transaction', sa.Column('transaction_score', sa.Integer(), nullable=True))
    op.add_column('booksapp_users', sa.Column('userscore', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booksapp_users', 'userscore')
    op.drop_column('booksapp_transaction', 'transaction_score')
    op.drop_column('booksapp_transaction', 'transaction_remove_ts')
    op.drop_column('booksapp_transaction', 'transaction_book_ts')
    # ### end Alembic commands ###
