"""empty message

Revision ID: 975eabe80445
Revises: 
Create Date: 2021-09-12 21:24:12.929204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975eabe80445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booksapp_transaction', 'transaction_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booksapp_transaction', 'transaction_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
