"""empty message

Revision ID: 98f37ec17684
Revises: 58a46b04aa04
Create Date: 2021-10-18 23:23:57.762445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f37ec17684'
down_revision = '58a46b04aa04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    #op.drop_index('idx_booksapp_store_store_location', table_name='booksapp_store')
    op.add_column('booksapp_users', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('booksapp_users', sa.Column('verified_on', sa.DateTime(), nullable=True))
    op.add_column('booksapp_users', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booksapp_users', 'created_on')
    op.drop_column('booksapp_users', 'verified_on')
    op.drop_column('booksapp_users', 'verified')
    op.create_index('idx_booksapp_store_store_location', 'booksapp_store', ['store_location'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
