"""empty message

Revision ID: edba09ee86b1
Revises: 8b50e0ce4c5d
Create Date: 2022-02-24 14:57:28.064273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edba09ee86b1'
down_revision = '8b50e0ce4c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booksapp_invoice',
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice_status', sa.Text(), nullable=True),
    sa.Column('invoice_url', sa.Text(), nullable=True),
    sa.Column('invoice_total', sa.Text(), nullable=True),
    sa.Column('confirmed_usernumber', sa.BigInteger(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.add_column('booksapp_transaction', sa.Column('invoice_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booksapp_transaction', 'invoice_id')
    op.drop_table('booksapp_invoice')
    # ### end Alembic commands ###
